### ISSUE TITLE
Function names for exported functions

### ISSUE THREAD

**Issue by MarkEdmondson1234** [samterfa/googlePackageMaker#7]
It would be good to decide now on the naming conventions for exported functions, this is something I am revising and refactoring in my newer packages.

The suggested ideal is `noun_verb()` - lowercase snake case with an optional prefix such as `ga_` or `gar_` - reasons include for auto-complete to be easy to use.

With this in mind I propose the following changes to the functions so far:

* get_google_api() -> api_get()
* list_google_apis() -> api_list()
* make_google_package() -> package_make()

If using a prefix, perhaps `gpm_` for googlePackageMaker?

**Comment by samterfa** [comment]
Addressed

**Comment by samterfa** [comment]
I don't like prefixes though understand that autofill isn't as easy and function name collisions will happen more frequently. I opted for api_get(), api_list(), and package_make().

**Comment by samterfa** [comment]
I don't like prefixes though understand that autofill isn't as easy and function name collisions will happen more frequently. I opted for api_get(), api_list(), and package_make(). Happy to reconsider.
